# -*- coding: utf-8 -*-
"""Notebook_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NoQawciJlYcEesi1zwWLYBfgQdUujAlc
"""

num = int(input())
rank = ['A', 'B+', 'B', 'C+', 'C', 'D+', 'D', 'F']
step = 5
startpoint = 90
j = 0
while startpoint > 0:
  if num >= startpoint:
      print(rank[j])
      startpoint -= 100
  elif startpoint < 60:
      print(rank[j])
      startpoint -= 100
  startpoint -= step
  j += 1