# -*- coding: utf-8 -*-
"""Notebook_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NoQawciJlYcEesi1zwWLYBfgQdUujAlc
"""

'Sorting'
def selection_sort(arr):
     size = len(arr)
     for i in range(size - 1):
         min_index = i
         for j in range(min_index + 1, size):
             if arr[j] < arr[min_index]:
                 min_index = j

         if i != min_index:
             arr[i], arr[min_index] = arr[min_index], arr[i]

lst = []
while True:
     a = int(input().__str__())
     if a != 0:
         lst.append(a)

     if a == '0' or a == 0:
         break

if __name__ == '__main__':
     elements = lst
     selection_sort(elements)
     Choice_input = input()
     if Choice_input == 'min':
         for i in range(len(elements)):
             print(elements[i], end=' ')
     else:
         num = len(elements) - 1
         while num >= 0:
             print(elements[num], end=' ')
             num -= 1