# -*- coding: utf-8 -*-
"""Find_S.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AMOpKhHyd_RKx8K_Tz_RoE2dKlXWSF4z
"""

#Find-S Algorithm

def expand(X, S):  # เทียบ list S ปัจจุบัน ที่ X เปรียบไปตาม i
  
  for i in range(len(S)):   # find i order of S
    if X[i] != S[i] and S[i] == '':   # Add X[i] Attribute to S[i] (S[i] == '')
      S[i] = X[i]
    elif X[i] != S[i] and S[i] != '': # Add '?' to S[i] (S[i] != '')
      S[i] = '?'
  print(S)
  return S
  

def FindS(X, T): # Loop ที่นำ S ไปพิจารณาตาม T ว่าเป็น Yes or No ตามที่ list X 
  S = [''] * len(X[0])      # Define S follow len(X[0])
  for i in range(len(X)):   # find i order of X
    if T[i] == 'Yes':       # Check T[i] and i == i[X]
      S = expand(X[i], S)
      # print(S)   
  print(S)
  return S
  

if __name__ == '__main__':  # เป็นการบอกว่าไฟล์นี้เป็นไฟล์ที่ถูกประมวลผลเอง Task ตาม if นี้
  X = [['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same'],
       ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same'],
       ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change'],
       ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change']]
  T = ['Yes', 'Yes', 'No', 'Yes']
  
  S = FindS(X, T)