# -*- coding: utf-8 -*-
"""List-Then-Eliminate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CvRr_wOFy_Hb8-8nsbFxNyMLLbHMiEfN
"""

# List-Then-Elimination algorithm

import numpy as np

def ListElim(X,T):
  X = np.array(X)
  T = np.array(T)
  n = X.shape[1]
  A = []
  for i in range(n):
    A.append(sorted(list(set(X[:,i]))))

  H = []
  t = []
  i = 1

  idx_data = [0] * n
  while True:
    h = []
    for j in range(n):
      h.append(A[j][idx_data[j]])

    for tt in np.unique(T):
      if isConsisit(X, T, h, tt):
        H.append(h)
        t.append(tt)
        print(i, h, tt)
        i += 1
    
    idx_data[-1] += 1
    letter_index = n-1
    while idx_data[letter_index] > len(A[letter_index]) -1:
      idx_data[letter_index] = 0
      letter_index -= 1
      if letter_index < 0:
        return H, t
      idx_data[letter_index] += 1

  return H, t

def isConsisit(X,T,h,t):
  for i in range(len(X)):
    if h == list(X[i]):
      if T[i] != t:
        return False
  return True

if __name__ == '__main__':  # เป็นการบอกว่าไฟล์นี้เป็นไฟล์ที่ถูกประมวลผลเอง Task ตาม if นี้
  X = [['Sunny', 'Warm', 'Normal', 'Strong', 'Warm', 'Same'],
       ['Sunny', 'Warm', 'High', 'Strong', 'Warm', 'Same'],
       ['Rainy', 'Cold', 'High', 'Strong', 'Warm', 'Change'],
       ['Sunny', 'Warm', 'High', 'Strong', 'Cool', 'Change']]
  T = ['Yes', 'Yes', 'No', 'Yes']
  
  H, t = ListElim(X, T)